# Generated by Django 3.2.9 on 2021-12-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app_1', '0002_fba_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fba_suggestion',
            name='plain_carton_line_item',
        ),
        migrations.AddField(
            model_name='fba_suggestion',
            name='site',
            field=models.CharField(default='amazon.de', max_length=300),
        ),
    ]
