# Generated by Django 3.2.9 on 2021-12-02 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app_1', '0006_auto_20211202_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fba',
            name='client',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
